<?php

namespace AppBundle\Repository;

/**
 * SquareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SquareRepository extends \Doctrine\ORM\EntityRepository
{
}
