app:
    resource: "@AppBundle/Controller/"
    type:     annotation

places:
    type:  rest
    resource: AppBundle\Controller\PlaceController

users:
    type: rest
    resource: AppBundle\Controller\UserController

prices:
    type: rest
    resource: AppBundle\Controller\PriceController

categories:
    type:     rest
    resource: AppBundle\Controller\CategoryController

preferences:
    type:  rest
    resource: AppBundle\Controller\PreferenceController